# Generated by Django 5.0.7 on 2024-08-31 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', 'Specialties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileverifyrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='verification',
            field=models.CharField(choices=[('verified', 'Профиль подтвержден'), ('on_verification', 'Профиль на проверке'), ('not_verified', 'Профиль не подтвержден'), ('rejected', 'Профиль не прошел проверку')], default='not_verified', max_length=20),
        ),
        migrations.AddField(
            model_name='profileverifyrequest',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='verification',
            field=models.CharField(choices=[('verified', 'Профиль подтвержден'), ('on_verification', 'Профиль на проверке'), ('not_verified', 'Профиль не подтвержден'), ('rejected', 'Профиль не прошел проверку')], default='not_verified', max_length=20),
        ),
    ]
