# Generated by Django 5.0.7 on 2024-09-01 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', 'Specialties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='reply_reload_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 1, 8, 23, 23, 864223, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
