# Generated by Django 5.0.7 on 2024-08-21 07:34

import Profiles.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('region', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('short_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_visibility', models.BooleanField(default=True)),
                ('email_visibility', models.BooleanField(default=True)),
                ('logo_img', models.ImageField(blank=True, height_field=220, null=True, upload_to=Profiles.models.image_upload_to, width_field=220)),
                ('telegram_link', models.URLField(blank=True, null=True)),
                ('vk_link', models.URLField(blank=True, null=True)),
                ('timezone', models.IntegerField(null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('link_to_company', models.URLField()),
                ('company_name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('object_id', models.UUIDField()),
                ('file', models.FileField(upload_to=Profiles.models.verification_files_upload)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileVerifyRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('object_id', models.UUIDField()),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_visibility', models.BooleanField(default=True)),
                ('email_visibility', models.BooleanField(default=True)),
                ('logo_img', models.ImageField(blank=True, height_field=220, null=True, upload_to=Profiles.models.image_upload_to, width_field=220)),
                ('telegram_link', models.URLField(blank=True, null=True)),
                ('vk_link', models.URLField(blank=True, null=True)),
                ('timezone', models.IntegerField(null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('education_program', models.CharField(choices=[('bachelor', 'Бакалавриат'), ('magistracy', 'Магистратура'), ('specialty', 'Специалитет')], max_length=11, null=True)),
                ('form_of_education', models.CharField(choices=[('full_time', 'Очная форма обучения'), ('part_time', 'Заочная форма обучения'), ('full_part_time', 'Очно-Заочная форма обучения')], max_length=15, null=True)),
                ('speciality', models.CharField(max_length=50, null=True)),
                ('admission_year', models.IntegerField(null=True)),
                ('skills', models.ManyToManyField(related_name='skills', to='Profiles.skill')),
                ('user', models.OneToOneField(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='university', to='Profiles.university')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
