# Generated by Django 5.0.7 on 2024-08-18 09:51

import Profiles.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('region', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(unique=True)),
                ('short_name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=15)),
                ('phone_visibility', models.BooleanField(default=False)),
                ('email_visibility', models.BooleanField(default=False)),
                ('logo_img', models.ImageField(blank=True, height_field=220, null=True, upload_to=Profiles.models.image_upload_to, width_field=220)),
                ('telegram_link', models.CharField(blank=True, null=True)),
                ('vk_link', models.CharField(blank=True, null=True)),
                ('timezone', models.IntegerField()),
                ('verification', models.CharField(choices=[('verified', 'Профиль подтвержден'), ('on_verification', 'Профиль на проверке'), ('not_verified', 'Профиль не подтвержден'), ('not_accepted', 'Профиль не прошел проверку')], default='not_verified')),
                ('link_to_company', models.CharField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=15)),
                ('phone_visibility', models.BooleanField(default=False)),
                ('email_visibility', models.BooleanField(default=False)),
                ('logo_img', models.ImageField(blank=True, height_field=220, null=True, upload_to=Profiles.models.image_upload_to, width_field=220)),
                ('telegram_link', models.CharField(blank=True, null=True)),
                ('vk_link', models.CharField(blank=True, null=True)),
                ('timezone', models.IntegerField()),
                ('verification', models.CharField(choices=[('verified', 'Профиль подтвержден'), ('on_verification', 'Профиль на проверке'), ('not_verified', 'Профиль не подтвержден'), ('not_accepted', 'Профиль не прошел проверку')], default='not_verified')),
                ('form_of_education', models.CharField(choices=[('full_time', 'Очная форма обучения'), ('part_time', 'Заочная форма обучения'), ('full_part_time', 'Очно-Заочная форма обучения')])),
                ('speciality', models.CharField(max_length=50)),
                ('admission_year', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('university', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Profiles.university')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
