# Generated by Django 5.0.7 on 2024-08-29 15:06

import Profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=10000, upload_to=Profiles.models.verification_files_upload),
        ),
    ]
