# Generated by Django 5.0.7 on 2024-09-01 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0003_alter_studentprofile_reply_reload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='reply_reload_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 1, 8, 11, 31, 290736, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
