# Generated by Django 5.0.7 on 2024-09-18 11:22

import Files.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('object_id', models.UUIDField()),
                ('file', models.FileField(max_length=200, upload_to='', validators=[Files.models.validate_file_type, Files.models.validate_file_size])),
                ('type', models.CharField(choices=[('verification_file', 'Файлы верификации'), ('task_file', 'Файлы задач'), ('solution_file', 'Файлы решений')], max_length=20)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
