# Generated by Django 5.0.7 on 2024-09-28 05:55

import Files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0002_alter_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=200, upload_to=Files.models.get_file_path, validators=[Files.models.validate_file_type, Files.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('verification_file', 'Файлы верификации'), ('task_file', 'Файлы задач'), ('solution_file', 'Файлы решений'), ('chat_file', 'Файлы чатов'), ('message_file', 'Файлы сообщения')], max_length=20),
        ),
    ]
