# Generated by Django 5.0.7 on 2024-09-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', 'TaskPatterns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='file',
        ),
    ]
