# Generated by Django 5.0.7 on 2024-09-28 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_remove_task_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='file',
        ),
    ]
