# Generated by Django 5.0.7 on 2024-08-29 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificationcode',
            options={'ordering': ['-created_at']},
        ),
    ]
