# Generated by Django 5.0.7 on 2024-09-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['created_at']},
        ),
    ]
